
select * from customer limit 20

--q1.What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--q2. which customers used discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--Q3.which are the top 5 with the avg review rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) as "Average product rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4.compare the average purchase amount between standard and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do subscribed customer spend more? Compare average spend and total revenue between subcribers and non-subscribers?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND (SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6.Which 5 products have the highest percentage of prchase with discount applied?
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' then 1 else 0 end)/count(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. segement customer into new, return, loyal based on their total
--number of previous purchases,and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases =1 then 'NEW'
	when previous_purchases between 2 and  10 then 'RETURNING'
	else 'LOYAL'
	end as customer_segment
from customer
)

select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment

--Q8. What are the top most purchased products within each category?
with item_counts as(
select category,
item_purchased, 
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc )as item_rank
from customer
group by category,item_purchased
)

select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--Q9.are customer who are repeat buyers are likely to subscriber?
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases>5
group by subscription_status

--Q10. wshat is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



